import { SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import AdminPageHeader from "@/components/admin/admin-header";
import { AdminSidebar } from "@/components/admin/admin-sidebar";
import { CSSProperties } from "react";
  
  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <>
      <SidebarProvider 
      style={{
    "--sidebar-width": "16rem",
    "--sidebar-width-mobile": "20rem",
  }as CSSProperties & { [key: string]: string }}
  >
      <div className="flex h-screen w-full overflow-hidden">
        {/* Sidebar */}
        <AdminSidebar/>

        {/* Main Content */}
        <div className="flex flex-col flex-1 w-full overflow-auto">
          {/* Header */}
          <AdminPageHeader
            userName="Devanjan"
            userProfileUrl="https://github.com/shadcn.png"
          />

          {/* Page Content */}
          <main className="flex-1 overflow-auto bg-gradient-to-br from-gray-100 to-gray-400 dark:bg-inherit">
            {children}
          </main>
        </div>
      </div>
    </SidebarProvider> 
      </>
    );
  }

